# Generated by Django 3.1.5 on 2021-02-01 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SQUA', 'SQUA'), ('SCO', 'SCO'), ('PERE', 'PERE')], max_length=100, verbose_name='Nombre')),
                ('number', models.IntegerField(verbose_name='Numero de tarjeta')),
                ('owner', models.CharField(max_length=150, verbose_name='Titular')),
                ('credit_limit', models.IntegerField(verbose_name='Limite de credito')),
                ('expiration_date', models.DateField(verbose_name='Vencimiento de la tarjeta')),
                ('rate', models.FloatField(verbose_name='Tasa')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.personas', verbose_name='Persona')),
            ],
            options={
                'db_table': 'Tarjetas',
            },
        ),
    ]
